@test_dotnet_HostAddress = http://localhost:5024

POST {{test_dotnet_HostAddress}}/api/ai/GetAiResponse
Content-Type: application/json
Accept: application/json

{
  "prompt": "hello there"
}

###

POST {{test_dotnet_HostAddress}}/api/ai/createjob
Content-Type: application/json
Accept: application/json

{
  "title": "Janitor",
  "description": "rofeko sp. z o.o. od 15 lat specjalizująca się w dostawie rozwiązań IT z zakresu finansów i logistyki poszukuje do swojego zespołu osoby na stanowisko Programista. Zakres obowiązków Tworzenie oraz utrzymanie oprogramowania w oparciu o środowisko .NET Praca z bazami danych MSSQL (tworzenie zapytań, widoków, procedur oraz funkcji SQL) Wymagania Wykształcenie wyższe techniczne Doświadczenie w programowaniu w technologii.NET(C#) Znajomość technologii WinForms Znajomość języka T-SQL oraz relacyjnych baz danych Doświadczenie w pracy z Git Samodzielność, umiejętność analitycznego myślenia i rozwiązywania problemów Umiejętność czytania dokumentacji technicznej Gotowość do pracy stacjonarnej w siedzibie firmy Mile widziane Znajomość kontrolek DevExpress"
}

###

POST {{test_dotnet_HostAddress}}/api/ai/searchjobs
Content-Type: application/json
Accept: application/json

{
  "prompt": "starting career in it"
}

###
